version: '3.8'

services:
  apg-postgres:
    image: postgres
    container_name: apg_db
    restart: always
    ports:
      - 25060:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s

volumes:
  postgres:
    name: apg-db
